anchor_version = "0.22.1"
solana_version = "1.8.16"

[features]
seeds = true

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "tests/dummy.json"

[scripts]
test = "yarn mocha"

[programs.mainnet]
arrow_sunny = "ARoWLTBWoWrKMvxEiaE2EH9DrWyV7mLpKywGDWxBGeq9"

[programs.devnet]
arrow_sunny = "ARoWLTBWoWrKMvxEiaE2EH9DrWyV7mLpKywGDWxBGeq9"

[programs.testnet]
arrow_sunny = "ARoWLTBWoWrKMvxEiaE2EH9DrWyV7mLpKywGDWxBGeq9"

[programs.localnet]
arrow_sunny = "ARoWLTBWoWrKMvxEiaE2EH9DrWyV7mLpKywGDWxBGeq9"

[[test.genesis]]
address = "SPQR4kT3q2oUKEJes2L6NNSBCiPW9SfuhkuqC9bp6Sx"
program = "./artifacts/programs/sunny.so"

[[test.genesis]]
address = "QMNeHCGYnLVDn1icRAfQZpjPLBNkfGbSKRB83G5d8KB"
program = "./artifacts/programs/quarry_mine.so"

[[test.genesis]]
address = "QMWoBmAyJLAsA1Lh9ugMTw2gciTihncciphzdNzdZYV"
program = "./artifacts/programs/quarry_mint_wrapper.so"
